[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ci_anchor_test = "2E2tM56x3tKFqTvsqsCjo2ywyzV2jRat1dUyVD2pQAtQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/millie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
